version: '3'
services:

  server:
    image: datastewardshipwizard/wizard-server
    restart: always
    ports:
      - 3000:3000
    volumes:
      - /dsw/server/application.yml:/application/engine-wizard/config/application.yml:ro
      - /dsw/server/integration.yml:/application/engine-wizard/config/integration.yml:ro
      - /dsw/templates/dmp:/application/engine-wizard/templates/dmp:ro

  client:
    image: datastewardshipwizard/wizard-client
    restart: always
    ports:
      - 80:80
    environment:
      API_URL: http://localhost:3000

  docworker:
    image: datastewardshipwizard/document-worker
    restart: always
    volumes:
      - /dsw/docworker/config.yml:/app/config.yml:ro
      - /dsw/templates/dmp:/app/templates:ro

  rabbitmq:
    image: rabbitmq:3.8.2-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: password

  mongo:
    image: mongo:4.2.3
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /dsw/data:/data/db
    command: mongod
