version: '3'
services:

  server:
    image: datastewardshipwizard/wizard-server
    restart: always
    ports:
      - 3000:3000
    volumes:
      - /dsw/application.yml:/application/engine-wizard/config/application.yml
      - /dsw/integration.yml:/application/engine-wizard/config/integration.yml
    links:
      - mongo

  client:
    image: datastewardshipwizard/wizard-client
    restart: always
    ports:
      - 80:80
    environment:
      API_URL: http://localhost:3000

  mongo:
    image: mongo:4.0.12
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /dsw/data:/data/db
    command: mongod
